### ISSUE TITLE
fastq format long read file input?

### ISSUE THREAD

**Issue by goshng** [holtjma/fmlrc#22] opened 2023-06-02 07:40 UTC
Hi,

I guess that fmlrc does not accept a fastq format file for long reads because I have the following message in a fmlrc run
ERROR: input long reads must be in FASTA format - file must end in '.fasta' or '.fa'

I usually correct sequence assemblies in fasta format. But, I need to polish raw long reads before assembling to locate genes in the reads. Is there an easier way of polishing long reads using fmlrc?

One thing I could do is that I could
1. convert a fastq file to a FASTA format file
2. polish long reads in the FASTA format file
3. put the polished long reads back to the starting fastq file.

But, I am sure whether there is such a tool.

Thank you,

Sang

**Comment by goshng** [comment] 2023-06-02 08:10
I guess that I could convert fastq to fasta, polish the fasta, and put the fasta to fastq. But, the fmlrc could change the lengths of the sequences in the fasta during polishing. Right? Is there a way of keeping the length unchanged in the fmlrc? Or, could recommend any other polishing tools to polish without changing the sequence lengths? I appreciate your help. Thank you!

**Comment by holtjma** [comment] 2023-06-02 11:19
Fmlrc2 (https://github.com/HudsonAlpha/fmlrc2) can handle fastq files as input, but it will still produce a fasta output.  This is primarily because correction changes the sequence length, so quality values become highly ambiguous, especially for anything newly inserted.  I’m unaware of a tool that tries to keep quality, but I haven’t looked recently either.

**Comment by goshng** [comment] 2023-06-03 01:02
Thank you very much for the response. Because I am using ptGAUL(https://github.com/Bean061/ptgaul) in which I just have been following the polishing routine, I have to use Fmlrc not Fmlrc2. Either way, the polishing step would change the lengths of sequences, so I am kind of stuck in my problem. I am unaware of polishing steps, so could you point me to any other polishing tools that keep the sequence length unchanged?

Any way, thank you for the great polishing tool, fmlrc. It is a great polishing tool.

**Comment by holtjma** [comment] 2023-06-03 16:32
fmlrc and fmlrc2 should give near identical results (it was designed to just be faster and easier to use).  

Regardless, I’m unaware of a tool that can meet your need of outputting quality while polishing or correcting, but I also have not kept up with it.

**Comment by holtjma** [comment] 2023-06-08 16:19
Closing for now, but feel free to reopen if you have more questions.

**Closed as completed by holtjma** 2023-06-08 16:19 UTC
